[package]
name = "native_dsp"
version = "0.1.0"
edition = "2021"

[lib]
name = "native_dsp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.5", features = ["extension-module"] }
numpy = { version = "0.22.1" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
